### ISSUE TITLE
Autocomplete on aliased fields not working correctly in GraphiQL UI

### ISSUE THREAD

**Issue by bxtp4p** [Jahia/graphql-core#9]
When aliasing a field in a query, the autocomplete hints that are shown are incorrect. 

For example, here's the hints for a non-aliased property: 

![image](https://user-images.githubusercontent.com/10562371/58128632-b79cb480-7bdd-11e9-9b7e-7884c83579c2.png)

And when aliased:

![image](https://user-images.githubusercontent.com/10562371/58128586-9fc53080-7bdd-11e9-92fa-e5d1ed54b9c4.png)

The hints for the aliased field are incorrect. It looks like it shows fields for JCRNode vs. JCRProperty (in this example).

The same issue was reported and fixed in the original GraphiQL code base: https://github.com/graphql/graphiql/issues/222

**Comment by Fgerthoffert** [comment]
The GraphiQL version was updated recently, preventing this from happening
